# Generated by Django 4.2.11 on 2024-09-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('galaxy', models.CharField(max_length=20)),
                ('queued_jobs', models.IntegerField()),
                ('running_jobs', models.IntegerField()),
                ('failed_jobs', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pulsar')),
            ],
        ),
    ]
