# Generated by Django 4.2.11 on 2024-09-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='pulsar',
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
