# Generated by Django 4.2.11 on 2025-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_history_pulsar_alter_history_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RRDPulsar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rrd_path', models.CharField(max_length=255)),
                ('galaxy', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
