# Generated by Django 4.2.17 on 2025-04-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rrdpulsar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('galaxy', models.CharField(max_length=20)),
                ('queued_jobs_month_avg', models.IntegerField()),
                ('running_jobs_month_avg', models.IntegerField()),
                ('failed_jobs_month_avg', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('galaxy', models.CharField(max_length=20)),
                ('queued_jobs_hour_avg', models.IntegerField()),
                ('running_jobs_hour_avg', models.IntegerField()),
                ('failed_jobs_hour_avg', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('galaxy', models.CharField(max_length=20)),
                ('queued_jobs_day_avg', models.IntegerField()),
                ('running_jobs_day_avg', models.IntegerField()),
                ('failed_jobs_day_avg', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PulsarActiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('job_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PulsarLongestJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PulsarMostUsedTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=100)),
                ('job_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=20)),
                ('dest_id', models.CharField(max_length=20)),
                ('release', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='RRDPulsar',
        ),
        migrations.AddField(
            model_name='pulsar',
            name='anonymous_jobs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulsar',
            name='unique_users',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulsarmostusedtools',
            name='pulsar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mostusedtools', to='core.pulsar'),
        ),
        migrations.AddField(
            model_name='pulsarlongestjobs',
            name='pulsar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longestjobs', to='core.pulsar'),
        ),
        migrations.AddField(
            model_name='pulsaractiveusers',
            name='pulsar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activeusers', to='core.pulsar'),
        ),
    ]
