# Generated by Django 4.2.17 on 2025-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galaxy_historyfinal_historymonth_historyyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsar',
            name='anonymous_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pulsar',
            name='failed_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pulsar',
            name='queued_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pulsar',
            name='running_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pulsar',
            name='unique_users',
            field=models.IntegerField(default=0),
        ),
    ]
