# Generated by Django 4.2.17 on 2025-05-04 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pulsar_anonymous_jobs_alter_pulsar_failed_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulestats',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedulestats',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='schedulestats',
            name='release',
        ),
        migrations.RemoveField(
            model_name='schedulestats',
            name='start',
        ),
        migrations.AddField(
            model_name='schedulestats',
            name='bounded_slowndown',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schedulestats',
            name='mean_slowndown',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schedulestats',
            name='response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schedulestats',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
