# Generated by Django 4.2.11 on 2025-05-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_schedulestats_end_remove_schedulestats_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='failed_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='queued_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='running_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyfinal',
            name='failed_jobs_month_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyfinal',
            name='queued_jobs_month_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyfinal',
            name='running_jobs_month_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historymonth',
            name='failed_jobs_hour_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historymonth',
            name='queued_jobs_hour_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historymonth',
            name='running_jobs_hour_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyyear',
            name='failed_jobs_day_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyyear',
            name='queued_jobs_day_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyyear',
            name='running_jobs_day_avg',
            field=models.IntegerField(default=0),
        ),
    ]
