# Generated by Django 4.2.17 on 2025-09-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_history_failed_jobs_alter_history_queued_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='influxdb_host',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galaxy',
            name='influxdb_password_var_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galaxy',
            name='influxdb_port',
            field=models.IntegerField(default=8086),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='influxdb_username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galaxy',
            name='pbs_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
